In [22]:
from framework.dataprovider import *
from keras.models import Sequential
from keras.layers.core import Dense, Activation
from keras.optimizers import SGD
import numpy as np

rng = np.random.RandomState(123456)

timehorizons = [1, 2, 4, 10, 25, 50, 100]
timehorizons = [1, 2, 4]
shapes = []
scores = []
testRatios = []
numEpochs = 5

for timehorizon in timehorizons:
    print 'testing %s' % timehorizon
    rng.seed(123456)
    dp = TimeWindowDataProvider(timehorizon, rng=rng)
    data, targets = dp.getTrainingData()
    shapes.append(data.shape)
    model = Sequential()
    model.add(Dense(output_dim=300, input_dim=data.shape[1], init="he_normal"))
    model.add(Activation("sigmoid"))
    model.add(Dense(output_dim=300, input_dim=300, init="he_normal"))
    model.add(Activation("sigmoid"))
    model.add(Dense(output_dim=300, input_dim=300, init="he_normal"))
    model.add(Activation("sigmoid"))
    model.add(Dense(output_dim=targets.shape[1], init="he_normal"))
    model.add(Activation("softmax"))
    
    #sgd = SGD(lr=0.1, decay=1e-2, momentum=0.5, nesterov=True)
    model.compile(loss='categorical_crossentropy', optimizer='rmsprop')
    print 'training model'
    model.fit(data, targets, show_accuracy=True, nb_epoch=numEpochs)
    
    testData, testTargets = dp.getTestData()
    testRatios.append(float(np.sum(testTargets[:,0]))/testTargets.shape[0])
    predictions = model.predict(testData)
    ac = np.argmax(predictions, axis=-1)
    score = np.sum(testTargets[xrange(ac.shape[0]), ac])/float(testTargets.shape[0])
    
    #score = model.evaluate(testData, testTargets)
    scores.append(score)
    
print "%-15s | %-15s | %-10s | %-5s" % ('time horizon', 'shape', 'test ratio', 'score')
print '--------------------------------------------'
for i in xrange(len(timehorizons)):
    print "%-15s | %-15s | %-10s | %-5s" % (timehorizons[i], shapes[i], testRatios[i], scores[i])


testing 1
training model
Epoch 1/5
3534/3534 [==============================] - 1s - loss: 0.7702 - acc: 0.4966     
Epoch 2/5
3534/3534 [==============================] - 0s - loss: 0.7167 - acc: 0.5150     
Epoch 3/5
3534/3534 [==============================] - 0s - loss: 0.7217 - acc: 0.5068     
Epoch 4/5
3534/3534 [==============================] - 0s - loss: 0.7139 - acc: 0.5170     
Epoch 5/5
3534/3534 [==============================] - 1s - loss: 0.7062 - acc: 0.5224     
testing 2
training model
Epoch 1/5
3533/3533 [==============================] - 3s - loss: 0.7711 - acc: 0.4965     
Epoch 2/5
3533/3533 [==============================] - 3s - loss: 0.7319 - acc: 0.4965     
Epoch 3/5
3533/3533 [==============================] - 4s - loss: 0.7284 - acc: 0.5047     
Epoch 4/5
3533/3533 [==============================] - 3s - loss: 0.7182 - acc: 0.5027     
Epoch 5/5
3533/3533 [==============================] - 3s - loss: 0.7130 - acc: 0.4984     
testing 4
training model
Epoch

In [19]:
print "%-15s | %-15s | %-10s | %-10s | %-5s" % ('time horizon', 'shape', 'test ratio', 'added', 'score')
print '--------------------------------------------'
for i in xrange(len(timehorizons)):
    print "%-15s | %-15s | %.8f | %.8f | %.8f" % (timehorizons[i], shapes[i], testRatios[i], testRatios[i] + scores[i], scores[i])

time horizon    | shape           | test ratio | added      | score
--------------------------------------------
1               | (3534, 388)     | 0.53316327 | 1.25888377 | 0.72572050
2               | (3533, 1940)    | 0.57397959 | 1.31394959 | 0.73997000
4               | (3531, 5044)    | 0.50765306 | 1.20084993 | 0.69319687


In [10]:
predictions = model.predict(testData)

In [18]:
for elem in zip(predictions[:10], testTargets[:10]):
    print elem

(array([ 0.62336582,  0.37663418]), array([ 1.,  0.]))
(array([ 0.62336582,  0.37663418]), array([ 0.,  1.]))
(array([ 0.6235494,  0.3764506]), array([ 1.,  0.]))
(array([ 0.6235494,  0.3764506]), array([ 0.,  1.]))
(array([ 0.62336582,  0.37663418]), array([ 0.,  1.]))
(array([ 0.6235494,  0.3764506]), array([ 1.,  0.]))
(array([ 0.6235494,  0.3764506]), array([ 0.,  1.]))
(array([ 0.62336582,  0.37663418]), array([ 1.,  0.]))
(array([ 0.62336582,  0.37663418]), array([ 1.,  0.]))
(array([ 0.62336582,  0.37663418]), array([ 1.,  0.]))


In [21]:
from framework.dataprovider import *
from keras.models import Sequential
from keras.layers.core import Dense, Activation
from keras.optimizers import SGD
import numpy as np

rng = np.random.RandomState(123456)

timehorizons = [1, 2, 4, 10, 25, 50, 100]
timehorizons = [3]
shapes = []
scores = []
testRatios = []
numEpochs = 20

for timehorizon in timehorizons:
    print 'testing %s' % timehorizon
    rng.seed(123456)
    dp = TimeWindowBestPerformingDataProvider(timehorizon, rng=rng)
    data, targets = dp.getTrainingData()
    trainingChange, testChange = dp.getChange()
    shapes.append(data.shape)
    model = Sequential()
    model.add(Dense(output_dim=300, input_dim=data.shape[1], init="he_normal"))
    model.add(Activation("sigmoid"))
    model.add(Dense(output_dim=300, input_dim=300, init="he_normal"))
    model.add(Activation("sigmoid"))
    model.add(Dense(output_dim=300, input_dim=300, init="he_normal"))
    model.add(Activation("sigmoid"))
    model.add(Dense(output_dim=targets.shape[1], init="he_normal"))
    model.add(Activation("softmax"))
    
    sgd = SGD(lr=0.1, decay=5e-3, momentum=0.3, nesterov=True)
    #model.compile(loss='categorical_crossentropy', optimizer='rmsprop')
    model.compile(loss='categorical_crossentropy', optimizer=sgd)
    print 'training model'
    model.fit(data, targets, show_accuracy=True, nb_epoch=numEpochs)
    
    testData, testTargets = dp.getTestData()
    testRatios.append(float(np.sum(testTargets[:,0]))/testTargets.shape[0])
    predictions = model.predict(testData)
    ac = np.argmax(predictions, axis=-1)
    score = np.sum(testTargets[xrange(ac.shape[0]), ac])/float(testTargets.shape[0])
    
    #score = model.evaluate(testData, testTargets)
    scores.append(score)
    
print "%-15s | %-15s | %-10s | %-5s" % ('time horizon', 'shape', 'test ratio', 'score')
print '--------------------------------------------'
for i in xrange(len(timehorizons)):
    print "%-15s | %-15s | %-10s | %-5s" % (timehorizons[i], shapes[i], testRatios[i], scores[i])



testing 3
training model
Epoch 1/20
3532/3532 [==============================] - 3s - loss: 3.9820 - acc: 0.2200     
Epoch 2/20
3532/3532 [==============================] - 3s - loss: 3.5707 - acc: 0.2585     
Epoch 3/20
3532/3532 [==============================] - 3s - loss: 3.4833 - acc: 0.2622     
Epoch 4/20
3532/3532 [==============================] - 3s - loss: 3.4714 - acc: 0.2520     
Epoch 5/20
3532/3532 [==============================] - 3s - loss: 3.3973 - acc: 0.2828     
Epoch 6/20
3532/3532 [==============================] - 2s - loss: 3.3738 - acc: 0.2820     
Epoch 7/20
3532/3532 [==============================] - 2s - loss: 3.3561 - acc: 0.2845     
Epoch 8/20
3532/3532 [==============================] - 2s - loss: 3.3404 - acc: 0.2888     
Epoch 9/20
3532/3532 [==============================] - 2s - loss: 3.3328 - acc: 0.2877     
Epoch 10/20
3532/3532 [==============================] - 2s - loss: 3.3236 - acc: 0.2877     
Epoch 11/20
3532/3532 [=====================

In [22]:
predictions = model.predict(testData)

i = 0
optimal = 0
predicted = 0
for elem in zip(np.argmax(predictions[:10], axis = -1), np.argmax(testTargets[:10], axis = -1)):
    print elem, testChange[i, elem[0]], testChange[i, elem[1]]
    optimal += testChange[i, elem[1]]
    predicted += testChange[i, elem[0]]
    i += 1
    
print optimal
print predicted

(17, 227) -15.54 1.1216
(376, 376) 5.81 5.81
(376, 61) -14.312 21.42
(376, 17) -13.693 2.12
(376, 348) -3.69 2.3534
(376, 376) 7.224 7.224
(376, 331) -5.483 1.3651
(376, 17) -2.326 1.74
(17, 340) 0.0 2.987
(376, 376) 28.453 28.453
74.5941
-13.557
